language: php

php:
  - 5.4

before_script:
  - wget -nc http://getcomposer.org/composer.phar
  - php composer.phar install

before_script:
    - createdb orm_behaviors_test
    - "echo 'create extension cube;' | psql orm_behaviors_test"
    - "echo 'create extension earthdistance;' | psql orm_behaviors_test"

script: phpunit

after_script:
    - dropdb orm_behaviors_test
